### ISSUE TITLE
Button sometimes displays abnormally

### ISSUE THREAD

**Issue by liuxiaocs7** [tonngw/leetcode-helper#4]
The effect looks like as follow:

![image](https://user-images.githubusercontent.com/42756849/212125317-e487140c-1be6-4819-81cf-9a495e40e119.png)

And x is undefined.

![image](https://user-images.githubusercontent.com/42756849/212125426-18d344c9-8caa-429a-97fe-3389cec6a1fc.png)

![image](https://user-images.githubusercontent.com/42756849/212125812-5419f844-134e-47d3-888b-84df35d84242.png)

**Comment by tonngw** [comment]
Sorry, this problem does exist, my implementation is to wait until the page is loaded before adding the button to the page, but leetcode loads asynchronously, sometimes the page is loaded but the element to fetch has not been loaded, which will cause an error and eventually fail to load buttons.
Solution: Generally refresh is OK, if there is time later I will continue to improve.

**Comment by liuxiaocs7** [comment]
> Sorry, this problem does exist, my implementation is to wait until the page is loaded before adding the button to the page, but leetcode loads asynchronously, sometimes the page is loaded but the element to fetch has not been loaded, which will cause an error and eventually fail to load buttons. Solution: Generally refresh is OK, if there is time later I will continue to improve.

Sorry for late, thanks for your kindly reply and detailed explanation,  also for sharing such a useful tool, looking forward to your update! :)

**Comment by tonngw** [comment]
> > Sorry, this problem does exist, my implementation is to wait until the page is loaded before adding the button to the page, but leetcode loads asynchronously, sometimes the page is loaded but the element to fetch has not been loaded, which will cause an error and eventually fail to load buttons. Solution: Generally refresh is OK, if there is time later I will continue to improve.
> 
> Sorry for late, thanks for your kindly reply and detailed explanation, also for sharing such a useful tool, looking forward to your update! :)

Hello, this tool was updated yesterday to support the leetcode latest version. Welcome to use it. I will close this issue.

**Comment by liuxiaocs7** [comment]
Hi, @tonngw, Thanks for your replyt, I updated the script to the latest version 1.1.2, but it is not displayed. 

![image](https://github.com/tonngw/leetcode-helper/assets/42756849/96c57eae-5f90-489e-ad04-914a2129333e)

After switch to the new UI, the display is normal. Does the script only support the new UI now?

![image](https://github.com/tonngw/leetcode-helper/assets/42756849/936217a4-b597-47d6-8b5c-aea7b6d49464)

**Comment by tonngw** [comment]
Yes, I'm sorry. considering that most people have switched to the new version of LeetCode and the official website is gradually improving the new version, So only provide support for the new version.

**Comment by tonngw** [comment]
In addition, I recommend that you use the new version of Leetcode. Although I was a bit not accustomed to use it at first, I gradually found that the user experience was actually quite good.

**Comment by liuxiaocs7** [comment]
Thank you for your explanation and recommendation, I will try it :)
